In [19]:
import torch
import numpy as np

## Tensores
A tensor is a number, vector, matrix, or any n-dimensional array. Let's create a tensor with a single number.

In [3]:
t = torch.tensor(3.)
t

tensor(3.)

Tensors can have any number of dimensions and different lengths along each dimension. We can inspect the length along each dimension using the .shape property of a tensor.
We can verify this by checking the dtype attribute of our tensor.

In [6]:
t = torch.tensor([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12.]]
])
print(t)
print(t.shape)
print(t.dtype)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])
torch.Size([2, 2, 3])
torch.float32


## Tensor operations and gradients

We can combine tensors with the usual arithmetic operations. Let's look at an example:

In [7]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

We've created three tensors: x, w, and b, all numbers. w and b have an additional parameter requires_grad set to True. We'll see what it does in just a moment.

Let's create a new tensor y by combining these tensors.

In [8]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, y is a tensor with the value 4 * 3 + 5 = 17. 

What makes PyTorch unique is that we can automatically compute the derivative of y w.r.t. the tensors that have requires_grad set to True i.e. w and b. This feature of PyTorch is called autograd (automatic gradients).

To compute the derivatives, we can invoke the .backward method on our result y.

In [9]:
# Compute derivatives
y.backward()

The derivatives of y with respect to the input tensors are stored in the .grad property of the respective tensors.



In [10]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


The "grad" in w.grad is short for gradient, which is another term for derivative. The term gradient is primarily used while dealing with vectors and matrices.

## Tensor functions

Apart from arithmetic operations, the `torch` module also contains many functions for creating and manipulating tensors. Let's look at some examples.

In [1]:
# Tensor con forma y valores aleatorios
w = torch.randn(2, 3, requires_grad=True)

NameError: name 'torch' is not defined

In [14]:
# Create a tensor with a fixed value for every element
t_full = torch.full((3, 2), 42)
t_full

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [15]:
# Concatenate two tensors with compatible shapes

t_full_2 = torch.full((3, 2), 13)

t_cat = torch.cat((t_full, t_full_2))
t_cat

tensor([[42, 42],
        [42, 42],
        [42, 42],
        [13, 13],
        [13, 13],
        [13, 13]])

In [16]:
# Compute the sin of each element
t_sin = torch.sin(t_cat)
t_sin

tensor([[-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [ 0.4202,  0.4202],
        [ 0.4202,  0.4202],
        [ 0.4202,  0.4202]])

In [18]:
# Change the shape of a tensor
t_rshape = t_full.reshape(1,1,2,3)
t_rshape

tensor([[[[42, 42, 42],
          [42, 42, 42]]]])

In [20]:
# Convert the numpy array to a torch tensor.

x = np.array([[1, 2], [3, 4.]])
x

y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [21]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])